[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy && node src/app.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
